name: social_sync
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

  # ------------- Packages -------------- #
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages

  intl: ^0.19.0
  lottie: ^3.1.2
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  connectivity_plus: ^6.0.5
  cached_network_image: ^3.4.0
  flutter_native_splash: ^2.4.1
  smooth_page_indicator: ^1.2.0+3

  # Web Specific
  http: ^1.2.2

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3

  # ------------- Packages End ------------ #

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # ------------ Local Assets ------------- #
  assets:
    - assets/logos/
    - assets/app_logo/
    - assets/images/content/
    - assets/images/animations/
    - assets/images/on_boarding_images/

  # ----------- Local Fonts --------------- #
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\Poppins-Bold.ttf
          weight: 800
